feat: DOCS-171 - Improve routes-generator.py to handle service update
- Added the 'add' subcommand:
  If this is the first time the service is installed in the node (server),
  then this subcommand generates the service-resolver, the service-router
  and the service hcl configuration files. Otherwise, it generates only the
  service hcl configuration file

- Added the 'regenerate subcommand:
  It should be used after the service instance is removed from the node (server).
  It regenerates the service-resolver and service-router configs containing
  ids of all the instances already registered without the deleted one.
  It works only when consul does not have a registered service in this node,
  otherwise the script returns an error

- Updated the setup script to correctly call the python script adding
  the error handling when the script fails

diff --git a/package/carbonio-docs-editor b/package/carbonio-docs-editor
--- a/package/carbonio-docs-editor
+++ b/package/carbonio-docs-editor
@@ -24,13 +24,19 @@ fi
 # Limit secret visibility as much as possible
 export -n SETUP_CONSUL_TOKEN
 
-# Generate service-router, service-resolver config and update carbonio-docs-editor.hcl
-serviceId=$(uuidgen)
+# Generate service-router, service-resolver config and carbonio-docs-editor.hcl
 python3 /usr/lib/carbonio-docs-routes-generator.py \
+  add \
   -s carbonio-docs-editor \
   -p service_id \
-  -i "$serviceId" \
   -d /etc/carbonio/docs-editor/service-discover/
+
+if [[ "$?" != "0" ]]; then
+  echo "The generation of the carbonio-docs-editor configs files failed"
+  echo "(see /usr/lib/carbonio-docs-routes-generator.py)"
+  exit 1;
+fi
+
 
 POLICY_NAME='carbonio-docs-editor-policy'
 POLICY_DESCRIPTION='Carbonio Docs Editor service policy for service and sidecar proxy'
